### PR TITLE
Separate layout and convert content to markdown

### PR DESCRIPTION
**Pull request by mbreit**
To support translations of the site, I converted the page content to
markdown and use jekyll to generate html and include the layout.

Backward incompatible changes:
- I removed the embedded anchor tags within the headlines to clean up
  the resulting markdown. The ids for linking to the sections are now
  generated by jekyll and change for some headlines (for example "How
  can I help" was #help before and is now #how-can-i-help).
- There has been a typo in the sidebar in the slack channel link that
  caused the rest of the sidebar to disappear in most browsers.
  I fixed the link so the rest of the sidebar is visible now.

### CODE REVIEW

**Comment by sangyye** [comment]
:+1:

**Comment by mbreit** [comment]
Btw: Github just build my fork with these changes at http://mbreit.github.io/refugees/

**Comment by sangyye** [comment]
@mbreit This looks really good. Thanks for doing this. And Markdown makes things so much easier :smile:

**Comment by jhilden** [comment]
great thanks.  this will be a great base for hopefully merging in @khaledalhasan's arabaic translation at the next meeting

**Pull request merged**
